export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";
export const MOVIE_LOADED = "GET_MOVIE";
export const MOVIE_LOADING = "MOVIE_LOADING";
export const CLEAR_MOVIE = "CLEAR_MOVIE";
export const LOAD_TRAILER = "LOAD_TRAILER";
export const UNLOAD_TRAILER = "UNLOAD_TRAILER";
export const SEARCH_MOVIE = "SEARCH_MOVIE";
export const SEARCH_FINISHED = "SEARCH_FINISHED";
export const SEARCH_FAIL = "SEARCH_FAIL";
export const LOADING_SEARCH = "LOADING_SEARCH";
export const NEXT_PAGE_LOADED = "NEXT_PAGE_LOADED";
export const LOADING_MORE = "LOADING_MORE";
export const UPDATE_FILTER = "UPDATE_FILTER";
export const POPULAR_MOVIES_LOADED = "POPULAR_MOVIES_LOADED";
export const TRENDING_MOVIES_LOADED = "TRENDING_MOVIES_LOADED";
export const DASHBOARD_MOVIES_LOADED = "DASHBOARD_MOVIES_LOADED";
export const DASHBOARD_TV_LOADED = "DASHBOARD_TV_LOADED";
export const GENRES_LOADED = "GENRES_LOADED";
export const PARTIAL_GENRE_MOVIES_LOADED = "PARTIAL_GENRE_MOVIES_LOADED";
export const RANDOM_GENRES_SELECTED = "RANDOM_GENRES_SELECTED";
export const MOVIE_CREDITS_LOADED = "MOVIE_CREDITS_LOADED";
export const DASHBOARD_TOP_CONTENT_LOADED = "DASHBOARD_TOP_CONTENT_LOADED";
export const DASHBOARD_TOP_CONTENT_LOADED_FIN =
  "DASHBOARD_TOP_CONTENT_LOADED_FIN";

export const LOADING_TV_DETAILS = "LOADING_TV_DETAILS";
export const TV_DETAILS_LOADED = "TV_DETAILS_LOADED";
export const TV_CREDITS_LOADING = "TV_CREDITS_LOADING";
export const TV_CREDITS_LOADED = "TV_CREDITS_LOADED";

export const PERSON_DATA_LOADING = "PERSON_DATA_LOADING";
export const PERSON_DATA_LOADED = "PERSON_DATA_LOADED";

export const CLEAR_DASHBOARD = "CLEAR_DASHBOARD";

// Auth Types
export const AUTH_LOADING = "AUTH_LOADING";
export const CLEAR_AUTH_ERRORS = "CLEAR_AUTH_ERRORS";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const AUTH_FAILED = "AUTH_FAILED";
export const PROFILE_LOADED = "PROFILE_LOADED";
export const AUTH_CHECK_SUCCESS = "AUTH_CHECK_SUCCESS";
export const AUTH_CHECK_FAIL = "AUTH_CHECK_FAIL";
export const USER_LIST_LOADED = "USER_LIST_LOADED";
export const USER_LOGOUT_SUCCESS = "USER_LOGOUT_SUCCESS";

// User Actions
export const CONTENT_ADDED_TO_WATCH = "CONTENT_ADDED_TO_WATCH";
export const CONTENT_REMOVED_FROM_WATCH = "CONTENT_REMOVED_FROM_WATCH";
export const CONTENT_ADDED_TO_LIST = "CONTENT_ADDED_TO_LIST";
export const CONTENT_ADDED_TO_WATCHLIST = "CONTENT_ADDED_TO_WATCHLIST";
export const CONTENT_REMOVED_FROM_LIST = "CONTENT_REMOVED_FROM_LIST";
export const CONTENT_RATING_ADDED = "CONTENT_RATING_ADDED";
export const CONTENT_RATING_REMOVED = "CONTENT_RATING_REMOVED";
export const CONTENT_RATING_UPDATED = "CONTENT_RATING_UPDATED";
export const CREATE_LIST = "CREATE_LIST";
export const DELETE_LIST = "DELETE_LIST";
export const DELETING_LIST = "DELETING_LIST";
export const LIST_DELETED = "LIST_DELETED";
export const CONTENT_CLEARED = "CONTENT_CLEARED";

export const LIST_DATA_RECEIVED = "LIST_DATA_RECEIVED";
export const CONTENT_STATS_RECEIVED = "CONTENT_STATS_RECEIVED";
export const CUSTOM_LIST_DATE_RECEIVED = "CUSTOM_LIST_DATA_RECEIVED";
